[package]
name = "velorix-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { workspace = true }
futures = "0.3"
object_store = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
