[package]
name = "velorix-ingest-writer"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = { workspace = true }
arrow = { workspace = true, features = ["ipc"] }
async-trait = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
kube = { workspace = true, features = ["client", "ring", "rustls-tls"] }
object_store = { workspace = true, features = ["aws"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
velorix-control = { path = "../velorix-control" }
velorix-k8s = { path = "../velorix-k8s" }
velorix-storage = { path = "../velorix-storage" }
