[package]
name = "velorix-cli"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
object_store = { workspace = true, features = ["aws"] }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }
velorix-runtime = { path = "../velorix-runtime" }
velorix-storage = { path = "../velorix-storage" }

[dev-dependencies]
bytes = { workspace = true }
tempfile = { workspace = true }
