//! Narrow metadata administration facade for API control-plane wiring.

pub use velorix_meta::{
    validate_bearer_token, AcquireStandingRuntimeOwnerOutcome, AcquireStandingRuntimeOwnerRequest,
    BeginViewBootstrapOutcome, BeginViewBootstrapRequest, BeginViewDependencyEdgeV1,
    CaptureIngestSourceCutRequest, CaptureRelationIngestSourceCutRequest, CommitIngestRangeOutcome,
    FixViewBootstrapActivationCutOutcome, FixViewBootstrapActivationCutRequest, GrpcMetaStore,
    InMemoryMetaStore, IngestRangeReservation, IngestSourceCutV1, IngestSourceRelationIdentityV1,
    MetaStore, MetaStoreError, PromoteViewBootstrapOutcome, PromoteViewBootstrapRequest,
    PublishIngestReservationOutcome, PublishStandingRuntimeCheckpointOutcome,
    PublishStandingRuntimeCheckpointRequest, RelationIngestCapability,
    RelationIngestPartitionCutV1, RelationIngestPublicationRefV1, RelationIngestSourceCutV1,
    RelationPartitionAuthorityKey, ReserveIngestRangeOutcome, StandingRuntimeCheckpointPointer,
    StandingRuntimeFencingCapability, StandingRuntimeOwnerClaim, StandingRuntimeOwnerToken,
    StoreRelationCatalogOutcome, ViewBootstrapControlV1, ViewBootstrapLifecycleV1,
    INGEST_SOURCE_IDENTITY_GENERATION_V1, RELATION_INGEST_SOURCE_CUT_SCHEMA_VERSION_V1,
    STANDING_RUNTIME_BACKEND_TIME_SOURCE_RAFT_REPLICATED,
    STANDING_RUNTIME_FENCING_CAPABILITY_SCHEMA_VERSION,
    STANDING_RUNTIME_LEASE_AUTHORITY_KIND_HIQLITE_RAFT_SERIALIZED,
    STANDING_RUNTIME_LEASE_AUTHORITY_KIND_RAFT_REPLICATED_TIME,
    STANDING_RUNTIME_LEASE_EXPIRY_SEMANTICS_BACKEND_WALL_CLOCK_TTL,
    STANDING_RUNTIME_LEASE_EXPIRY_SEMANTICS_OPERATION_DRIVEN_LOGICAL,
    STANDING_RUNTIME_OUTPUT_COMMIT_REF_PREFIX, STANDING_RUNTIME_OUTPUT_DELTA_REF_PREFIX,
    STANDING_RUNTIME_OUTPUT_MANIFEST_REF_PREFIX,
    STANDING_RUNTIME_OWNER_SCOPE_KIND_TENANT_PROGRAM_VIEW,
};
