#!/usr/bin/env bash
set -euo pipefail
umask 077

case "$-" in
  *x*)
    echo "Refusing to run with shell xtrace enabled because auth secrets would be logged" >&2
    exit 64
    ;;
esac

repo_root="$(git rev-parse --show-toplevel)"
product_dir="${VELORIX_VIND_PRODUCT_DIR:-target/velorix-product}"
auth_env_file="${VELORIX_API_AUTH_ENV:-${product_dir}/api-auth.env}"
endpoint_url="${VELORIX_INGRESS_ENDPOINT_URL:-}"
ingress_controller="${VELORIX_INGRESS_CONTROLLER:-}"
external_hostname="${VELORIX_INGRESS_EXTERNAL_HOSTNAME:-}"
output_file="${VELORIX_INGRESS_TLS_AUTH_ATTESTATION_FILE:-${product_dir}/ingress-tls-auth-attestation.json}"
local_scratch_dir="${VELORIX_LOCAL_SCRATCH_DIR:-${product_dir}/scratch}"

usage() {
  cat <<'EOF'
Generate public ingress/TLS/auth evidence for an existing vind product slice.

Usage:
  VELORIX_INGRESS_ENDPOINT_URL=https://velorix.example.com \
  VELORIX_INGRESS_CONTROLLER=nginx \
  scripts/attest-vind-product-ingress.sh

Main environment overrides:
  VELORIX_VIND_PRODUCT_DIR=target/velorix-product
  VELORIX_API_AUTH_ENV=target/velorix-product/api-auth.env
  VELORIX_INGRESS_ENDPOINT_URL=https://velorix.example.com
  VELORIX_INGRESS_CONTROLLER=nginx
  VELORIX_INGRESS_EXTERNAL_HOSTNAME=velorix.example.com
  VELORIX_INGRESS_TLS_AUTH_ATTESTATION_FILE=target/velorix-product/ingress-tls-auth-attestation.json
  VELORIX_LOCAL_SCRATCH_DIR=target/velorix-product/scratch

The script reads the bearer tokens generated by scripts/run-vind-product.sh from
api-auth.env, calls scripts/attest-ingress-tls-auth.sh against the external HTTPS
endpoint, and writes a target-backed attestation file. It does not edit
product-evidence.json; rerun scripts/run-vind-product.sh with
VELORIX_INGRESS_TLS_AUTH_ATTESTATION_FILE to consume the evidence.
EOF
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
  usage
  exit 0
fi

if [ "$#" -ne 0 ]; then
  usage >&2
  exit 64
fi

require() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "missing required command: $1" >&2
    exit 127
  fi
}

cd "$repo_root"
require python3

if [ -z "$endpoint_url" ]; then
  echo "VELORIX_INGRESS_ENDPOINT_URL is required" >&2
  exit 64
fi
if [ -z "$ingress_controller" ]; then
  echo "VELORIX_INGRESS_CONTROLLER is required" >&2
  exit 64
fi

if [ -f "$auth_env_file" ]; then
  # shellcheck disable=SC1090
  source "$auth_env_file"
fi

extract_bearer_token() {
  python3 - "$1" <<'PY'
import re
import sys

header = sys.argv[1]
match = re.match(r"^\s*authorization\s*:\s*Bearer\s+(.+?)\s*$", header, re.IGNORECASE)
if match:
    print(match.group(1))
PY
}

api_token="${VELORIX_API_BEARER_TOKEN:-}"
admin_token="${VELORIX_ADMIN_BEARER_TOKEN:-}"
if [ -z "$api_token" ] && [ -n "${VELORIX_API_AUTH_HEADER:-}" ]; then
  api_token="$(extract_bearer_token "$VELORIX_API_AUTH_HEADER")"
fi
if [ -z "$admin_token" ] && [ -n "${VELORIX_ADMIN_AUTH_HEADER:-}" ]; then
  admin_token="$(extract_bearer_token "$VELORIX_ADMIN_AUTH_HEADER")"
fi

if [ -z "$api_token" ] || [ -z "$admin_token" ]; then
  echo "missing bearer tokens; run scripts/run-vind-product.sh first or set VELORIX_API_BEARER_TOKEN and VELORIX_ADMIN_BEARER_TOKEN" >&2
  echo "checked auth env: ${auth_env_file}" >&2
  exit 66
fi

mkdir -p "$product_dir"
VELORIX_INGRESS_ENDPOINT_URL="$endpoint_url" \
  VELORIX_API_BEARER_TOKEN="$api_token" \
  VELORIX_ADMIN_BEARER_TOKEN="$admin_token" \
  VELORIX_INGRESS_CONTROLLER="$ingress_controller" \
  VELORIX_INGRESS_EXTERNAL_HOSTNAME="$external_hostname" \
  VELORIX_INGRESS_TLS_AUTH_ATTESTATION_FILE="$output_file" \
  VELORIX_LOCAL_SCRATCH_DIR="$local_scratch_dir" \
  scripts/attest-ingress-tls-auth.sh

echo "ingress_tls_auth_attestation=${output_file}"
echo "consume_with=VELORIX_INGRESS_TLS_AUTH_ATTESTATION_FILE=${output_file} scripts/run-vind-product.sh"
